ForyouMel/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin', admin.site.urls),
    path('',include('homepage.urls'), name="homepage"),
    path('service/', include('service.urls'), name="service"),
    path('enquiry/', include('enquiry.urls'), name="enquiry"),
    path('shop/', include('shop.urls'), name="shop"),
    path('cart/', include('shopping_cart.urls')),
]

shop/flowers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.flower_en, name ="flower"),
    path('cn/', views.flower_cn, name="flower cn"),
    path('type/<type_id>', views.flower_type_en, name="flower type"),
    path('type/cn/<type_id>', views.flower_type_cn, name="flower type cn"),
    path('details/<id>/', views.flower_details_en, name="flower details"),
    path('details/cn/<id>/', views.flower_details_cn, name="flower details cn"),
    path('post_main_type/', views.post_flower_maintypes, name="flower main type post"),
    path('post_sub_type/', views.post_flower_subtypes, name="flower sub type post"),

]

shop/urls.py
from django.urls import path, include


urlpatterns = [
    path('flower/',include('shop.flowers.urls')),
    path('party_decoration/', include('shop.party_decoration.urls')),
    path('party/', include('shop.party_hire.urls')),
    path('wedding_floral/', include('shop.wedding_floral.urls')),

]

shop/flowers/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
from django.utils.safestring import mark_safe

from shop.models import Product, Type

class flower_type(Type):
    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['order']

class flower_sub_type(Type):
    order = models.PositiveIntegerField(default=0, blank=False, null=False)
    main_type = models.ForeignKey(flower_type, on_delete=models.CASCADE)
    class Meta(object):
        ordering = ['order']



class flower(Product):
    main_type = models.ForeignKey(flower_type, on_delete=models.CASCADE, null=True)
    type = models.ForeignKey(flower_sub_type, on_delete=models.CASCADE)
    order = models.PositiveIntegerField(default=0, blank=False, null=False)
    class Meta(object):
        ordering = ['order']

shop/flowers/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from .models import flower, flower_type, flower_sub_type
import json


# Create your views here.
def flower_en(request):
    if request.method == 'POST' and request.POST["language"] == "English":
        return redirect("flower")
    if request.method == 'POST' and request.POST["language"] == "Chinese":
        return redirect("flower cn")

    all_flowers = flower.objects.all()
    all_flower_types = flower_type.objects.all()
    all_flower_sub_types = flower_sub_type.objects.all()
    return render(request, 'flowers.html',
                  {'page_title': "Our Flowers", "types": all_flower_types, "sub_types": all_flower_sub_types,
                   "flowers": all_flowers})


def flower_cn(request):
    if request.method == 'POST' and request.POST["language"] == "English":
        return redirect("flower")
    if request.method == 'POST' and request.POST["language"] == "Chinese":
        return redirect("flower cn")
    all_flowers = flower.objects.all()
    all_flower_types = flower_type.objects.all()
    all_flower_sub_types = flower_sub_type.objects.all()
    return render(request, 'flowers_cn.html',
                  {'page_title': "花束 & 花卉", "types": all_flower_types, "sub_types": all_flower_sub_types,
                   "flowers": all_flowers})


def flower_type_en(request,type_id):
    if request.method == 'POST' and request.POST["language"] == "English":
        return redirect("flower type", type_id)
    if request.method == 'POST' and request.POST["language"] == "Chinese":
        return redirect("flower type cn", type_id)

    all_flowers = flower.objects.all()
    all_flower_types = flower_type.objects.all()
    all_flower_sub_types = flower_sub_type.objects.all()
    this_type = all_flower_sub_types.filter(id=type_id).first()

    return render(request, 'flowers_type.html',
                  {'page_title': "Our Flowers", "types": all_flower_types, "sub_types": all_flower_sub_types,
                   "flowers": all_flowers, "this_type": this_type})


def flower_type_cn(request, type_id):
    if request.method == 'POST' and request.POST["language"] == "English":
        return redirect("flower type", type_id)
    if request.method == 'POST' and request.POST["language"] == "Chinese":
        return redirect("flower type cn", type_id)

    all_flowers = flower.objects.all()
    all_flower_types = flower_type.objects.all()
    all_flower_sub_types = flower_sub_type.objects.all()
    this_type = all_flower_sub_types.filter(id=type_id).first()

    return render(request, 'flowers_type_cn.html',
                  {'page_title': "Our Flowers", "types": all_flower_types, "sub_types": all_flower_sub_types,
                   "flowers": all_flowers, "this_type": this_type})


def flower_details_en(request, id):
    if request.method == 'POST' and request.POST["language"] == "English":
        return redirect("flower details", id=id)
    if request.method == 'POST' and request.POST["language"] == "Chinese":
        return redirect("flower details cn", id=id)
    flower_detail = flower.objects.all().filter(id=id).first()
    all_flowers = flower.objects.all()
    all_flower_types = flower_type.objects.all()
    all_flower_sub_types = flower_sub_type.objects.all()
    flower_price_pair = json.loads(flower_detail.size_price_pair)["size_price_pair"]

    flower_price_pair_display = []
    for each in flower_price_pair:
        pair = each.split(",")
        flower_price_pair_display.append(f"{pair[0]} - ${pair[1]}")


    return render(request, 'flowers_details.html',
                  {'page_title': "Our Flowers: " + flower_detail.name_en, "flower": flower_detail, "types": all_flower_types, "sub_types": all_flower_sub_types,
                   "flowers": all_flowers,"price_pairs":flower_price_pair_display})


def flower_details_cn(request, id):
    if request.method == 'POST' and request.POST["language"] == "English":
        return redirect("flower details", id=id)
    if request.method == 'POST' and request.POST["language"] == "Chinese":
        return redirect("flower details cn", id=id)
    flower_detail = flower.objects.all().filter(id=id).first()
    flower_price_pair = json.loads(flower_detail.size_price_pair)["size_price_pair"]

    flower_price_pair_display = []
    for each in flower_price_pair:
        pair = each.split(",")
        flower_price_pair_display.append(f"{pair[0]} - ${pair[1]}")

    return render(request, 'flowers_details_cn.html',
                  {'page_title': "花束:" + flower_detail.name_cn, "flower": flower_detail,"price_pairs":flower_price_pair_display})


def post_flower_maintypes(request):
    if request.is_ajax and request.method == "POST":
        main_types = flower_type.objects.all()
        return_data = []
        for each in main_types:
            return_data.append([each.id, each.name_cn])
        return_data = json.dumps(return_data)
        return JsonResponse(return_data, status=200, safe=False)


def post_flower_subtypes(request):
    if request.is_ajax and request.method == "POST":
        main_type_id = request.POST.get("main_type_id", None)
        sub_types = flower_sub_type.objects.all().filter(main_type=main_type_id)
        return_data = []
        for each in sub_types:
            return_data.append([each.id, each.__str__()])

        return_data = json.dumps(return_data)
        return JsonResponse(return_data, status=200, safe=False)

shop/flowers/templates/flower_sub_menu.html
{% extends 'admin/change_form.html' %}

{% block field_sets %}
    {% for fieldset in adminform %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

        <fieldset class="module aligned {{ fieldset.classes }}">
            {% if fieldset.name %}<h2>{{ fieldset.name }}</h2>{% endif %}
            {% if fieldset.description %}
                <div class="description">{{ fieldset.description|safe }}</div>
            {% endif %}
            {% for line in fieldset %}
                {% for field in line %}{% if field.field.name != "type" %}
                    {% if field.field.name != "main_type" %}

                        <div class="form-row{% if line.fields|length_is:'1' and line.errors %} errors{% endif %}{% if not line.has_visible_field %} hidden{% endif %}{% for field in line %}{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% endfor %}">
                            {% if line.fields|length_is:'1' %}{{ line.errors }}{% endif %}
                            {% for field in line %}
                                <div{% if not line.fields|length_is:'1' %}
                                    class="fieldBox{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% if not field.is_readonly and field.errors %} errors{% endif %}{% if field.field.is_hidden %} hidden{% endif %}"{% elif field.is_checkbox %}
                                    class="checkbox-row"{% endif %}>
                                    {% if not line.fields|length_is:'1' and not field.is_readonly %}
                                        {{ field.errors }}{% endif %}
                                    {% if field.is_checkbox %}
                                        {{ field.field }}{{ field.label_tag }}
                                    {% else %}
                                        {{ field.label_tag }}
                                        {% if field.is_readonly %}
                                            <div class="readonly">{{ field.contents }}</div>
                                        {% else %}
                                            {{ field.field }}
                                        {% endif %}
                                    {% endif %}
                                    {% if field.field.help_text %}
                                        <div class="help">{{ field.field.help_text|safe }}</div>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}{% endif %}{% endfor %}
            {% endfor %}

            <div class="form-row field-main_type">
                <div>
                    <label class="required" for="id_main_type">Main type:</label>
                    <div class="related-widget-wrapper">
                        <select name="main_type" required="" id="id_main_type">
                            <option value="" selected="">---------</option>
                        </select>

                    </div>
                </div>
            </div>

            <div class="form-row field-type" style="visibility: hidden">
                <div>
                    <label class="required" for="id_type">Type:</label>
                    <div class="related-widget-wrapper">
                        <select name="type" required="" id="id_type">
                            <option value="" selected="">---------</option>
                        </select>

                    </div>
                </div>
            </div>
        </fieldset>
        <script>
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            var csrftoken = getCookie('csrftoken');


            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            $.ajax({
                type: 'POST',
                url: "{% url 'flower main type post' %}",
                data: null,
                success: function (response) {
                    var main_type = document.getElementsByName("main_type")[0]
                    JSON.parse(response).forEach(function (element) {
                        let opt = document.createElement('option');
                        opt.value = element[0];
                        opt.innerHTML = element[1]

                        main_type.appendChild(opt)
                    })


                }

            })

            let main_type = document.getElementsByName("main_type")[0]
            main_type.onchange = function () {
                console.log(main_type.value.length)
                if (main_type.value != 0) {
                    $.ajax({
                        type: 'POST',
                        url: "{% url 'flower sub type post' %}",
                        data: {"main_type_id": main_type.value},
                        success: function (response) {
                            console.log(response)

                            var sub_type = document.getElementsByClassName("field-type")[0]
                            sub_type.style.visibility = 'visible'

                            var sub_type_selector = document.getElementsByName("type")[0]
                            JSON.parse(response).forEach(function (element) {
                                let opt = document.createElement('option');
                                opt.value = element[0];
                                opt.innerHTML = element[1]

                                sub_type_selector.appendChild(opt)
                            })
                        }


                    })
                }
            }
        </script>
    {% endfor %}

{% endblock %}

shop/flowers/templates/flower_sub_menu2.html
{% extends 'admin/change_form.html' %}


{% block field_sets %}
    {% for fieldset in adminform %}
        {% include "admin/includes/fieldset.html" %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

        <script>
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            var csrftoken = getCookie('csrftoken');


            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
            document.getElementsByName("type")[0].innerHTML = null;
            sub_type = document.getElementsByClassName("field-type")[0]
            sub_type.style.visibility = "hidden"

            main_type_select = document.getElementsByName("main_type")[0]
            main_type_select.onchange = function () {
                if (main_type_select.value.length != 0) {
                    console.log(main_type_select.value)
                    $.ajax({
                        type: 'POST',
                        url: "{% url 'flower sub type post' %}",
                        data: {"main_type_id": main_type_select.value},
                        success: function (response) {
                            console.log(response)

                            var sub_type = document.getElementsByClassName("field-type")[0]
                            sub_type.style.visibility = 'visible'

                            var sub_type_selector = document.getElementsByName("type")[0]
                            document.getElementsByName("type")[0].innerHTML = null;

                            JSON.parse(response).forEach(function (element) {
                                let opt = document.createElement('option');
                                opt.value = element[0];
                                opt.innerHTML = element[1]

                                sub_type_selector.appendChild(opt)
                            })
                        }


                    })
                }
            }
        </script>
    {% endfor %}
{% endblock %}

shop/flowers/templates/flowers.html
{% extends "template.html" %}
{% load static %}
{% block content %}



    <!-- Masthead-->
    <header class="masthead" style="background-image: url('{% static "img/gallery/flower header.jpg" %}')">
        <div class="container" style="height: 300px">
            <div class="masthead-subheading"></div>
            <div class="masthead-heading text-uppercase"></div>
        </div>
    </header>
    <!-- Portfolio Grid-->


    <section class="page-section bg-light" id="portfolio">
        <div class="container">
            <div class="text-center">
                <h1 class="section-heading text-uppercase" style="font-size: 60px">Flowers</h1>
                <h3 class="section-subheading text-muted"></h3>
            </div>
            <div class="row">
                <div class="col-lg-4 col-sm-6 mb-4">
                    <!-- Portfolio item 1-->
                    <div class="portfolio-item">
                        <a class="portfolio-link" href="{% url "flower type" 2 %}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"></div>
                            </div>
                            <img class="img-fluid" src="{% static "img/flowers/rose bouquest 1.jpg" %}" alt="..."/>
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">Roses</div>
                            <div class="portfolio-caption-subheading text-muted">Rose bouquet</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 mb-4">
                    <!-- Portfolio item 1-->
                    <div class="portfolio-item">
                        <a class="portfolio-link" href="{% url "flower type" 1 %}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"></div>
                            </div>
                            <img class="img-fluid" src="{% static "img/flowers/rose bouquest 1.jpg" %}" alt="..."/>
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">Roses</div>
                            <div class="portfolio-caption-subheading text-muted">Rose bouquet</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 mb-4">
                    <!-- Portfolio item 1-->
                    <div class="portfolio-item">
                        <a class="portfolio-link" href="{% url "flower type" 1 %}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"></div>
                            </div>
                            <img class="img-fluid" src="{% static "img/flowers/rose bouquest 1.jpg" %}" alt="..."/>
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">Roses</div>
                            <div class="portfolio-caption-subheading text-muted">Rose bouquet</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 mb-4">
                    <!-- Portfolio item 1-->
                    <div class="portfolio-item">
                        <a class="portfolio-link" href="{% url "flower type" 1 %}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"></div>
                            </div>
                            <img class="img-fluid" src="{% static "img/flowers/rose bouquest 1.jpg" %}" alt="..."/>
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">Roses</div>
                            <div class="portfolio-caption-subheading text-muted">Rose bouquet</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 mb-4">
                    <!-- Portfolio item 1-->
                    <div class="portfolio-item">
                        <a class="portfolio-link" href="{% url "flower type" 1 %}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"></div>
                            </div>
                            <img class="img-fluid" src="{% static "img/flowers/rose bouquest 1.jpg" %}" alt="..."/>
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">Roses</div>
                            <div class="portfolio-caption-subheading text-muted">Rose bouquet</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 mb-4">
                    <!-- Portfolio item 1-->
                    <div class="portfolio-item">
                        <a class="portfolio-link" href="{% url "flower type" 2 %}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"></div>
                            </div>
                            <img class="img-fluid" src="{% static "img/flowers/rose bouquest 1.jpg" %}" alt="..."/>
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">Roses</div>
                            <div class="portfolio-caption-subheading text-muted">Rose bouquet</div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </section>

    <div style="position:fixed;margin-top: 8rem; margin-left: 5px">
        <div style="all: initial">
            <div class="header" style="width: 9rem">
                <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
                <div class="mega-category-menu" style="padding: 0;margin: 0;height: 30px;margin-left: 5px">
                    <span class="cat-button"><i class="lni lni-menu"></i>All Categories</span>
                    <ul class="sub-category">
                        {% for type in types %}
                            <li><a >{{ type.name_en }}<i
                                    class="lni lni-chevron-right"></i></a>
                                <ul class="inner-sub-category">
                                    {% for sub_type in sub_types %}
                                        {% if sub_type.main_type == type %}
                                            <li>
                                                <a href="{% url "flower type" sub_type.id %}">{{ sub_type.name_en }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

            </div>

        </div>
        <style>
            @media (min-width: 991px) {
                #mobile-nav {
                    display: none;
                }
            }
        </style>
        <div style="all: initial">
            <div class="header">

                <nav id="mobile-nav" class="navbar navbar-expand-lg">
                    <button style="max-width: 8rem" class="navbar-toggler mobile-menu-btn" type="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="toggler-icon"></span>
                        <span class="toggler-icon"></span>
                        <span class="toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                        <ul id="nav" class="navbar-nav ms-auto">

                            {% for type in types %}
                                <li class="nav-item">
                                    <a class="dd-menu collapsed" href="javascript:void(0)" data-bs-toggle="collapse"
                                       data-bs-target="#submenu-{{ type.name_en }}"
                                       aria-controls="navbarSupportedContent"
                                       aria-expanded="false" aria-label="Toggle navigation">{{ type.name_en }}</a>
                                    <ul class="sub-menu collapse" id="submenu-{{ type.name_en }}">
                                        {% for sub_type in sub_types %}
                                            {% if sub_type.main_type == type %}
                                                <li>
                                                    <a href="{% url "flower type" sub_type.id %}">{{ sub_type.name_en }}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endfor %}

                        </ul>
                    </div> <!-- navbar collapse -->
                </nav>
            </div>

        </div>

    </div>







{% endblock %}